ci_service: travis_pro
service_name: travis_pro
#repo_token: VobxuRqFdQZjT7HOM0nbeImW6Aib0O3zF
coverage_access_token: VobxuRqFdQZjT7HOM0nbeImW6Aib0O3zF
coverage_service: coveralls
scheme: MercadoPagoSDK
xcodeproj: MercadoPagoSDK/MercadoPagoSDK.xcodeproj
workspace: MercadoPagoSDK/MercadoPagoSDK.xcworkspace
build_directory: /Users/travis/Library/Developer/Xcode/DerivedData
source_directory:
   -LibraryComponents

