# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoPagoSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoPagoSDK
    pod 'MercadoPagoPXTracking', '2.0.0'
    pod 'MercadoPagoServices', '0.1.0-BETA-1'


  target 'MercadoPagoSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
